### ISSUE TITLE
Issue with other countries than Germany

### ISSUE THREAD

**Issue by pierre-py** [opus-42/eurostat-api-client#1]
Hello,

Thanks for this very useful function.

I tried to use it with the following specification. It works for Germany, but not for Italy or France. For the two latter countries, the data do not seem to be in the right order.

Thanks

    client = EurostatAPIClient(VERSION, FORMAT, LANGUAGE)
    params = {'unit':'I15','geo': 'FR','coicop':'CP00'}
    hicp_d = client.get_dataset('prc_hicp_midx',params=params) 
    hicp = hicp_d.to_dataframe() 
    hicp.plot()

**Comment by opus-42** [comment]
This issue should be solved by #2 . New package including this patch is going to be published soon on Pypi
