### ISSUE TITLE
Migrating to the New Eurostat API

### ISSUE THREAD

**Issue by derevirn** [opus-42/eurostat-api-client#10]
Hello @opus-42 , 

I recently visited the Eurostat website and saw the following warning message:

![Screenshot (2)](https://user-images.githubusercontent.com/9198526/183774859-aaa4c4c9-85ab-49ca-8c8c-ef8bd3a369bb.png)

Apparently, the current API will be deprecated by January 2023, as they are migrating to a new one. Thankfully, Eurostat posted a migration guide that includes all the differences between the two APIs, available [here](https://wikis.ec.europa.eu/display/EUROSTATHELP/API+Statistics+-+migrating+from+JSON+web+service+to+API+Statistics). I suggest updating the library code so it remains functional when the REST API is phased out, thank you.

Giannis Tolios

**Comment by opus-42** [comment]
Hello @derevirn, thank you for raising the issue. 

We should indeed prepare migration. I need to read more in details what it is going to change and if we need to do a major version or not. 

I would be additionally open to pull request & contribution on that repository if you would like to propose some solution.
Emmanuel

**Comment by derevirn** [comment]
Hello @opus-42,

Thanks for replying to my issue. I have checked the new specification, and compared the JSON files from the old and new endpoints. I believe it won't be difficult to update the library, as the changes are thankfully minor. I have forked the repository, so I will try to make the update myself. If I manage to accomplish that, I will submit a pull request and hopefully help you complete the migration.

Giannis

**Comment by opus-42** [comment]
Thank you I will take a look at it

**Comment by Basti3n** [comment]
@opus-42 
First of all, thank you for your work on the update and the library !

I have a question, you said on this [merge](https://github.com/opus-42/eurostat-api-client/commit/b0bc5b3a87119276aa93c7721de5bb01dc705b70) that you will `publish a new version` but it's been some days since the merge and I can't find the new update.

May we have ETA on it ? 

Thanks in advance !

**Comment by derevirn** [comment]
Hello @Basti3n . In the meantime, you can install directly from the main branch, by using the following command:

`pip install git+https://github.com/opus-42/eurostat-api-client#egg=eurostatapiclient`

**Comment by Basti3n** [comment]
First, thanks for your fast answer !

Second, I don't know if i should continue in this issue or create an other one, let met know and i'll create one, but i have a question.
The limitation `Add some filters (only mono-filtering is available for now)` is something limited with the new API ? I couldn't find the answer anywhere.

I used to have multiple param to make a complexe query, but now I can't find a way to use them. Is there any work around that can be done to unable multiple param ?

Thanks in advance !

**Comment by derevirn** [comment]
Hello @Basti3n , glad to help! I'm not really sure about this, as I added multiple parameters on my queries, and they seem to work fine. Try experimenting a bit, and create a new issue if you have any problems!

**Comment by opus-42** [comment]
Hello @Basti3n, sorry about this. I have just released a new version. This is now release and published to PyPi. 

Tell me if everything is now working properly with the new version :)
New version is 0.3.0

**Comment by Basti3n** [comment]
Hii !

You might have misstiped the version number, you named it `3.0.0`.
![image](https://user-images.githubusercontent.com/34554092/218432234-175139af-b23e-42ea-bf36-6f2f806ab0e0.png)

For the rest, everything looks perfect !
My issue was that some "key" had some new names. I changed them and it's all good !

Thanks for you update !

**Comment by opus-42** [comment]
Thanks for noticing the PyPi version is indeed 0.3.0 and not 3.0.0. I'll update the tag
