### ISSUE TITLE
getting eurostat dicts using client (question)

### ISSUE THREAD

**Issue by vedal** [opus-42/eurostat-api-client#5]
Thanks a lot for this simple client!
I was wondering if there's a simple way to get a dict of f.ex nace_r2 codes, similar to f.ex using this client

```
import eurostat
eurostat.get_dic('nace_r2')
```

Best

**Comment by opus-42** [comment]
Hello @vedal, sorry for the late answer. Currentm this no direct way to obtain this. A possibility would be as far as I understand to add metadata recuperation from the Eurostat metadata base [here](https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&dir=dic%2Ffr).

You could actually obtain the codes directly by downloading the relevant file (.dic files seems to actually be Tabbed-Separated Files, i.e. TSV).
